name: idfy_license_checker
description: A Dart package for verifying Indian Driving Licenses using IDfy APIs. Supports DL data extraction and government source verification.
version: 0.0.1
homepage: https://github.com/OmkarWalunj/idfy_license_checker
repository: https://github.com/OmkarWalunj/idfy_license_checker

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.24.9

flutter:
  uses-material-design: true
